{"sid": "e914ceb379a2411e87f0030122894d06", "uid": null, "qid": "e273507763244011adabd97cbf68c514", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [e273507763244011adabd97cbf68c514]\nTraceback (most recent call last):\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/openfabric/app/main.py\", line 92, in execute\n    msg , img , obj , sessid  = agent.Exec(user_prompt)\n  File \"/openfabric/app/Agent/agent.py\", line 76, in Exec\n    text = self.process(response)\n  File \"/openfabric/app/Agent/agent.py\", line 123, in process\n    self.exit(parsed)\n  File \"/openfabric/app/Agent/agent.py\", line 90, in exit\n    Agent.db.save_session(self.session_id,self.username,resp['summary'],Agent.sessions[self.session_id])\n  File \"/openfabric/app/Agent/Storage/VectorDB.py\", line 47, in save_session\n    self.save(session_id=session_id ,username = username ,summary=summary)\n  File \"/openfabric/app/Agent/Storage/VectorDB.py\", line 25, in save\n    self.cur.execute(\npsycopg2.errors.UndefinedTable: relation \"chats_index\" does not exist\nLINE 2:         INSERT INTO chats_index (session_id, username,summar...\n                            ^\n\n", "created_at": "2025-06-29T05:46:23.943486"}], "status": "FAILED", "created_at": "2025-06-29T05:46:20.765475", "updated_at": "2025-06-29T05:46:23.943546", "finished": true}