{"sid": "4f4fe4071d5f47fbbf9f2f3a00e64da9", "uid": null, "qid": "71c31e8363424811b7daddff70e667e6", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [71c31e8363424811b7daddff70e667e6]\nTraceback (most recent call last):\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/openfabric/app/app/main.py\", line 103, in execute\n    msg , img , obj , sessid  = agent.Exec(user_prompt)\n  File \"/openfabric/app/app/Agent/Agent.py\", line 65, in Exec\n    agent_response = self.exec(prompt)\n  File \"/openfabric/app/app/Agent/Agent.py\", line 89, in exec\n    processor_response = PROCESSOR.process()\n  File \"/openfabric/app/app/Agent/Agent.py\", line 156, in process\n    return self.generate_image(parsed)\n  File \"/openfabric/app/app/Agent/Agent.py\", line 199, in generate_image\n    self.session_data.set(IMAGE = self.generator.generate_image(image_description))\n  File \"/openfabric/app/app/main.py\", line 55, in generate_image\n    if OpenfabricGenerator._generator in None:\nTypeError: argument of type 'NoneType' is not iterable\n", "created_at": "2025-06-30T14:33:18.582492"}], "status": "FAILED", "created_at": "2025-06-30T14:32:26.982096", "updated_at": "2025-06-30T14:33:18.582513", "finished": true}