{"sid": "499c4d5504db40ceb981e3af9a041ead", "uid": null, "qid": "1b9767f09e4b40f7b59acda0c1b9001c", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [1b9767f09e4b40f7b59acda0c1b9001c]\nTraceback (most recent call last):\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/openfabric/app/main.py\", line 93, in execute\n    msg , img , obj , sessid  = agent.Exec(user_prompt)\n  File \"/openfabric/app/Agent/agent.py\", line 66, in Exec\n    self.EXIT()\n  File \"/openfabric/app/Agent/agent.py\", line 97, in EXIT\n    session_id=self.session_id,\nAttributeError: 'Agent' object has no attribute 'session_id'\n", "created_at": "2025-06-30T10:38:42.068123"}], "status": "FAILED", "created_at": "2025-06-30T10:38:25.946780", "updated_at": "2025-06-30T10:38:42.068152", "finished": true}