{"sid": "d6111eb5da724d20903e72ed317f2b30", "uid": null, "qid": "051fb3254a274374b91cd123bd1c0889", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [051fb3254a274374b91cd123bd1c0889]\nTraceback (most recent call last):\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/openfabric/app/main.py\", line 89, in execute\n    Agent.Init(OpenfabricGenerator())\n  File \"/openfabric/app/Agent/agent.py\", line 27, in Init\n    cls.load_prompts()\n  File \"/openfabric/app/Agent/agent.py\", line 52, in load_prompts\n    with open(Baseprompt_path,\"r\") as f:\nFileNotFoundError: [Errno 2] No such file or directory: '/openfabric/app/Agent/Prompts/BasePrompt copy.txt'\n", "created_at": "2025-06-29T12:57:27.528290"}], "status": "FAILED", "created_at": "2025-06-29T12:57:27.262401", "updated_at": "2025-06-29T12:57:27.528308", "finished": true}