{"sid": "f087d799ed6140878fd6a4b82dcd49b6", "uid": null, "qid": "2b4f99e6e03d478e9cbec32df52297fb", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [2b4f99e6e03d478e9cbec32df52297fb]\nTraceback (most recent call last):\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/openfabric/app/main.py\", line 92, in execute\n    msg , img , obj , sessid  = agent.Exec(user_prompt)\n  File \"/openfabric/app/Agent/agent.py\", line 74, in Exec\n    resp = self.exec(prompt)\n  File \"/openfabric/app/Agent/agent.py\", line 89, in exec\n    text = self.process(response)\n  File \"/openfabric/app/Agent/agent.py\", line 115, in process\n    elif state == States.QUERY:\n  File \"/usr/lib/python3.8/enum.py\", line 384, in __getattr__\n    raise AttributeError(name) from None\nAttributeError: QUERY\n", "created_at": "2025-06-29T13:05:09.965719"}], "status": "FAILED", "created_at": "2025-06-29T13:04:55.404586", "updated_at": "2025-06-29T13:05:09.965776", "finished": true}