{"sid": "c9d7507bc2be45cba575d1b7bf5cb233", "uid": null, "qid": "b01d36fbba374f84b7ad68745cadb7cc", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [b01d36fbba374f84b7ad68745cadb7cc]\nTraceback (most recent call last):\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/openfabric/app/main.py\", line 95, in execute\n    response: OutputClass = model.response\n  File \"/openfabric/app/Agent/agent.py\", line 71, in Exec\n    text = self.process(response)\n  File \"/openfabric/app/Agent/agent.py\", line 119, in process\n    return self.generate_image(parsed)\n  File \"/openfabric/app/Agent/agent.py\", line 95, in generate_image\n    self.image = Agent.generator.generate_image(image_description)\n  File \"/openfabric/app/main.py\", line 56, in generate_image\n    base64image  = base64.b64encode(image).decode(\"utf-8\")\nAttributeError: 'NoneType' object has no attribute 'get'\n", "created_at": "2025-06-28T15:27:12.497184"}], "status": "FAILED", "created_at": "2025-06-28T15:27:06.208344", "updated_at": "2025-06-28T15:27:12.497209", "finished": true}