{"sid": "29c2ecb2e82c48e486edca6d68a7a72b", "uid": null, "qid": "d18bfa4feec14ed5bf165b5b2baefb49", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [d18bfa4feec14ed5bf165b5b2baefb49]\nTraceback (most recent call last):\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/openfabric/app/main.py\", line 91, in execute\n    msg , img , obj , sessid  = agent.Exec(user_prompt)\n  File \"/openfabric/app/Agent/agent.py\", line 56, in Exec\n    agent_response = self.exec(prompt)\n  File \"/openfabric/app/Agent/agent.py\", line 78, in exec\n    processor_response = PROCESSOR.process()\n  File \"/openfabric/app/Agent/agent.py\", line 142, in process\n    return self.generate_model(parsed)\n  File \"/openfabric/app/Agent/agent.py\", line 183, in generate_model\n    self.session_data.set(OBJECT= self.generator.generate_3drender(self.session_data.IMAGE))\n  File \"/openfabric/app/main.py\", line 62, in generate_3drender\n    object = result.get('generated_object')\nAttributeError: 'NoneType' object has no attribute 'get'\n", "created_at": "2025-06-30T12:36:34.987445"}], "status": "FAILED", "created_at": "2025-06-30T12:36:08.825729", "updated_at": "2025-06-30T12:36:34.987503", "finished": true}