{"sid": "990eeda0ed0145ab8e491bf15748ebc4", "uid": null, "qid": "c7290b4d76c84ba0a28a39b550a296a3", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [c7290b4d76c84ba0a28a39b550a296a3]\nTraceback (most recent call last):\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/openfabric/app/main.py\", line 93, in execute\n    msg , img , obj , sessid  = agent.Exec(user_prompt)\n  File \"/openfabric/app/Agent/agent.py\", line 58, in Exec\n    agent_response = self.exec(prompt)\n  File \"/openfabric/app/Agent/agent.py\", line 86, in exec\n    processor_response = PROCESSOR.process()\n  File \"/openfabric/app/Agent/agent.py\", line 143, in process\n    return self.generate_image(parsed)\n  File \"/openfabric/app/Agent/agent.py\", line 183, in generate_image\n    self.session_data.set(IMAGE = self.generator.generate_image(image_description))\n  File \"/openfabric/app/main.py\", line 56, in generate_image\n    result = cls.stub.call(cls.app_ids[0], {'prompt':prompt}, 'super-user')\nAttributeError: type object 'OpenfabricGenerator' has no attribute 'stub'\n", "created_at": "2025-06-30T10:49:44.773544"}], "status": "FAILED", "created_at": "2025-06-30T10:49:33.919852", "updated_at": "2025-06-30T10:49:44.773583", "finished": true}