{"sid": "00229f0af5254df1931ac6d0d1334e54", "uid": null, "qid": "b577def38aa147c7b49e04086af26e6b", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [b577def38aa147c7b49e04086af26e6b]\nTraceback (most recent call last):\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/openfabric/app/app/main.py\", line 100, in execute\n    msg , img , obj , sessid  = agent.Exec(user_prompt)\n  File \"/openfabric/app/app/Agent/Agent.py\", line 59, in Exec\n    agent_response = self.exec(prompt)\n  File \"/openfabric/app/app/Agent/Agent.py\", line 83, in exec\n    processor_response = PROCESSOR.process()\n  File \"/openfabric/app/app/Agent/Processor.py\", line 44, in process\n    return self.recall_from_memory(parsed)\n  File \"/openfabric/app/app/Agent/Processor.py\", line 64, in recall_from_memory\n    refered_image_description=self.db.get_image_description(intent=intent)\n  File \"/openfabric/app/app/Agent/Storage/VectorDB.py\", line 24, in get_image_description\n    session_id = cls._vectorStore.get_session_id(intent=intent)\n  File \"/openfabric/app/app/Agent/Storage/VectorDB.py\", line 100, in get_session_id\n    cur.execute(\npsycopg2.errors.UndefinedTable: relation \"chat_index\" does not exist\nLINE 1: SELECT session_id FROM chat_index ORDER BY embedding <#> ARR...\n                               ^\n\n", "created_at": "2025-06-30T16:29:02.655506"}], "status": "FAILED", "created_at": "2025-06-30T16:28:59.409118", "updated_at": "2025-06-30T16:29:02.655562", "finished": true}