{"sid": "5459d61aa6dc4043827aeab7a1304a2c", "uid": null, "qid": "013aadcff3e540f39612e93a20db5744", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [013aadcff3e540f39612e93a20db5744]\nTraceback (most recent call last):\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/openfabric/app/main.py\", line 93, in execute\n    msg , img , obj , sessid  = agent.Exec(user_prompt)\n  File \"/openfabric/app/Agent/agent.py\", line 74, in Exec\n    self.EXIT()\n  File \"/openfabric/app/Agent/agent.py\", line 79, in EXIT\n    Agent.sessions[self.session_id] = self.llm.get_history()\n  File \"/openfabric/app/Agent/LLM/Gemini.py\", line 33, in get_history\n    return self.chat.get_history()\nAttributeError: 'GeminiLLM' object has no attribute 'chat'\n", "created_at": "2025-06-28T12:45:48.804593"}], "status": "FAILED", "created_at": "2025-06-28T12:45:36.991784", "updated_at": "2025-06-28T12:45:48.804632", "finished": true}