{"sid": "f961055363f5416586ad0607ad314dcf", "uid": null, "qid": "4f5a3b899c144e2a92d8ecc9d7f1cbf3", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [4f5a3b899c144e2a92d8ecc9d7f1cbf3]\nTraceback (most recent call last):\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/openfabric/app/main.py\", line 91, in execute\n    msg , img , obj , sessid  = agent.Exec(user_prompt)\n  File \"/openfabric/app/Agent/agent.py\", line 56, in Exec\n    agent_response = self.exec(prompt)\n  File \"/openfabric/app/Agent/agent.py\", line 78, in exec\n    processor_response = PROCESSOR.process()\n  File \"/openfabric/app/Agent/agent.py\", line 138, in process\n    return self.generate_image(parsed)\n  File \"/openfabric/app/Agent/agent.py\", line 179, in generate_image\n    self.session_data.set(IMAGE = self.generator.generate_image(image_description))\n  File \"/openfabric/app/main.py\", line 56, in generate_image\n    image = result.get('result')\nAttributeError: 'NoneType' object has no attribute 'get'\n", "created_at": "2025-06-30T12:32:30.498790"}], "status": "FAILED", "created_at": "2025-06-30T12:32:19.784298", "updated_at": "2025-06-30T12:32:30.498854", "finished": true}