{"sid": "bd77e50e70a84c0abb25945b2b48ef3d", "uid": null, "qid": "1b5b984dbed144cb8c894fcd686d59ed", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [1b5b984dbed144cb8c894fcd686d59ed]\nTraceback (most recent call last):\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/openfabric/app/main.py\", line 92, in execute\n    msg , img , obj , sessid  = agent.Exec(user_prompt)\n  File \"/openfabric/app/Agent/agent.py\", line 75, in Exec\n    resp = self.exec(prompt)\n  File \"/openfabric/app/Agent/agent.py\", line 90, in exec\n    text = self.process(response)\n  File \"/openfabric/app/Agent/agent.py\", line 122, in process\n    return self.generate_model(parsed)\n  File \"/openfabric/app/Agent/agent.py\", line 161, in generate_model\n    self.object = Agent.generator.generate_3drender(self.image)\n  File \"/openfabric/app/main.py\", line 62, in generate_3drender\n    object = result.get('generated_object')\nAttributeError: 'NoneType' object has no attribute 'get'\n", "created_at": "2025-06-29T15:44:07.453814"}], "status": "FAILED", "created_at": "2025-06-29T15:43:34.390442", "updated_at": "2025-06-29T15:44:07.453858", "finished": true}