{"sid": "cf55f9d709254232b15bd5cce7899d14", "uid": null, "qid": "ab774f6d445a44efba55c159193e31b3", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [ab774f6d445a44efba55c159193e31b3]\nTraceback (most recent call last):\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/openfabric/app/main.py\", line 92, in execute\n    msg , img , obj , sessid  = agent.Exec(user_prompt)\n  File \"/openfabric/app/Agent/agent.py\", line 81, in Exec\n    self.EXIT()\n  File \"/openfabric/app/Agent/agent.py\", line 101, in EXIT\n    Agent.db.save_session(self.session_id,self.username,self.image_desc,Agent.sessions[self.session_id])\n  File \"/openfabric/app/Agent/Storage/VectorDB.py\", line 91, in save_session\n    self.save(session_id=session_id ,username = username ,image_desc=image_desc)\n  File \"/openfabric/app/Agent/Storage/VectorDB.py\", line 101, in save\n    self.cur.execute(\nIndexError: tuple index out of range\n", "created_at": "2025-06-29T13:16:31.380925"}], "status": "FAILED", "created_at": "2025-06-29T13:16:03.126434", "updated_at": "2025-06-29T13:16:31.380982", "finished": true}