{"sid": "73c5fd8a40314d5db6fd1a1b0f695684", "uid": null, "qid": "f4cc839c2993417893ece721bf5ed8a6", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [f4cc839c2993417893ece721bf5ed8a6]\nTraceback (most recent call last):\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/action_dispatcher.py\", line 139, in process\n    output = self.workerContext.execution.execute(data, self.ray, self.state, update)\n  File \"/pysdk/.venv/lib/python3.8/site-packages/openfabric_pysdk/app/execution/application_interface.py\", line 66, in execute\n    self.execution_function(model)\n  File \"/openfabric/app/main.py\", line 92, in execute\n    msg , img , obj , sessid  = agent.Exec(user_prompt)\n  File \"/openfabric/app/Agent/agent.py\", line 75, in Exec\n    resp = self.exec(prompt)\n  File \"/openfabric/app/Agent/agent.py\", line 90, in exec\n    text = self.process(response)\n  File \"/openfabric/app/Agent/agent.py\", line 118, in process\n    return self.generate_image(parsed)\n  File \"/openfabric/app/Agent/agent.py\", line 157, in generate_image\n    self.image = Agent.generator.generate_image(image)\n  File \"/openfabric/app/main.py\", line 55, in generate_image\n    image = result.get('result')\nAttributeError: 'NoneType' object has no attribute 'get'\n", "created_at": "2025-06-29T14:50:35.435560"}], "status": "FAILED", "created_at": "2025-06-29T14:50:24.624238", "updated_at": "2025-06-29T14:50:35.435751", "finished": true}